// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/repository/interface.go
//
// Generated by this command:
//
//	mockgen -destination=../internal/repository/mocks.go -package=repository -source=../internal/repository/interface.go
//

// Package repository is a generated GoMock package.
package repository

import (
	channel "aggregator/src/internal/entity/channel"
	session "aggregator/src/internal/entity/session"
	transaction "aggregator/src/internal/transaction"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChannel is a mock of Channel interface.
type MockChannel struct {
	ctrl     *gomock.Controller
	recorder *MockChannelMockRecorder
	isgomock struct{}
}

// MockChannelMockRecorder is the mock recorder for MockChannel.
type MockChannelMockRecorder struct {
	mock *MockChannel
}

// NewMockChannel creates a new mock instance.
func NewMockChannel(ctrl *gomock.Controller) *MockChannel {
	mock := &MockChannel{ctrl: ctrl}
	mock.recorder = &MockChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannel) EXPECT() *MockChannelMockRecorder {
	return m.recorder
}

// LoadChannelList mocks base method.
func (m *MockChannel) LoadChannelList(ts transaction.Session) ([]channel.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadChannelList", ts)
	ret0, _ := ret[0].([]channel.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadChannelList indicates an expected call of LoadChannelList.
func (mr *MockChannelMockRecorder) LoadChannelList(ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadChannelList", reflect.TypeOf((*MockChannel)(nil).LoadChannelList), ts)
}

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// LoadOnlineSessionList mocks base method.
func (m *MockSession) LoadOnlineSessionList(ts transaction.Session) ([]session.OnlineSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadOnlineSessionList", ts)
	ret0, _ := ret[0].([]session.OnlineSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadOnlineSessionList indicates an expected call of LoadOnlineSessionList.
func (mr *MockSessionMockRecorder) LoadOnlineSessionList(ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadOnlineSessionList", reflect.TypeOf((*MockSession)(nil).LoadOnlineSessionList), ts)
}

// SaveChunkList mocks base method.
func (m *MockSession) SaveChunkList(ts transaction.Session, chunkList []session.Chunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChunkList", ts, chunkList)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChunkList indicates an expected call of SaveChunkList.
func (mr *MockSessionMockRecorder) SaveChunkList(ts, chunkList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChunkList", reflect.TypeOf((*MockSession)(nil).SaveChunkList), ts, chunkList)
}

// MockFlowBatch is a mock of FlowBatch interface.
type MockFlowBatch struct {
	ctrl     *gomock.Controller
	recorder *MockFlowBatchMockRecorder
	isgomock struct{}
}

// MockFlowBatchMockRecorder is the mock recorder for MockFlowBatch.
type MockFlowBatchMockRecorder struct {
	mock *MockFlowBatch
}

// NewMockFlowBatch creates a new mock instance.
func NewMockFlowBatch(ctrl *gomock.Controller) *MockFlowBatch {
	mock := &MockFlowBatch{ctrl: ctrl}
	mock.recorder = &MockFlowBatchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowBatch) EXPECT() *MockFlowBatchMockRecorder {
	return m.recorder
}

// LoadCommittedFileNames mocks base method.
func (m *MockFlowBatch) LoadCommittedFileNames(ts transaction.Session, nasIP string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCommittedFileNames", ts, nasIP)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadCommittedFileNames indicates an expected call of LoadCommittedFileNames.
func (mr *MockFlowBatchMockRecorder) LoadCommittedFileNames(ts, nasIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCommittedFileNames", reflect.TypeOf((*MockFlowBatch)(nil).LoadCommittedFileNames), ts, nasIP)
}

// RemoveByNasIP mocks base method.
func (m *MockFlowBatch) RemoveByNasIP(ts transaction.Session, nasIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveByNasIP", ts, nasIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveByNasIP indicates an expected call of RemoveByNasIP.
func (mr *MockFlowBatchMockRecorder) RemoveByNasIP(ts, nasIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveByNasIP", reflect.TypeOf((*MockFlowBatch)(nil).RemoveByNasIP), ts, nasIP)
}

// SaveFileNames mocks base method.
func (m *MockFlowBatch) SaveFileNames(ts transaction.Session, nasIP string, fileNameList []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFileNames", ts, nasIP, fileNameList)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFileNames indicates an expected call of SaveFileNames.
func (mr *MockFlowBatchMockRecorder) SaveFileNames(ts, nasIP, fileNameList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFileNames", reflect.TypeOf((*MockFlowBatch)(nil).SaveFileNames), ts, nasIP, fileNameList)
}

// MockFlow is a mock of Flow interface.
type MockFlow struct {
	ctrl     *gomock.Controller
	recorder *MockFlowMockRecorder
	isgomock struct{}
}

// MockFlowMockRecorder is the mock recorder for MockFlow.
type MockFlowMockRecorder struct {
	mock *MockFlow
}

// NewMockFlow creates a new mock instance.
func NewMockFlow(ctrl *gomock.Controller) *MockFlow {
	mock := &MockFlow{ctrl: ctrl}
	mock.recorder = &MockFlowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlow) EXPECT() *MockFlowMockRecorder {
	return m.recorder
}

// MoveFlowToTempDir mocks base method.
func (m *MockFlow) MoveFlowToTempDir(dirName, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveFlowToTempDir", dirName, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveFlowToTempDir indicates an expected call of MoveFlowToTempDir.
func (mr *MockFlowMockRecorder) MoveFlowToTempDir(dirName, fileName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveFlowToTempDir", reflect.TypeOf((*MockFlow)(nil).MoveFlowToTempDir), dirName, fileName)
}

// ReadFileNamesInFlowDir mocks base method.
func (m *MockFlow) ReadFileNamesInFlowDir(dirName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileNamesInFlowDir", dirName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileNamesInFlowDir indicates an expected call of ReadFileNamesInFlowDir.
func (mr *MockFlowMockRecorder) ReadFileNamesInFlowDir(dirName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileNamesInFlowDir", reflect.TypeOf((*MockFlow)(nil).ReadFileNamesInFlowDir), dirName)
}

// ReadFlow mocks base method.
func (m *MockFlow) ReadFlow(dirName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFlow", dirName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFlow indicates an expected call of ReadFlow.
func (mr *MockFlowMockRecorder) ReadFlow(dirName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFlow", reflect.TypeOf((*MockFlow)(nil).ReadFlow), dirName)
}

// ReadFlowDirNames mocks base method.
func (m *MockFlow) ReadFlowDirNames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFlowDirNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFlowDirNames indicates an expected call of ReadFlowDirNames.
func (mr *MockFlowMockRecorder) ReadFlowDirNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFlowDirNames", reflect.TypeOf((*MockFlow)(nil).ReadFlowDirNames))
}

// RemoveOld mocks base method.
func (m *MockFlow) RemoveOld(nasIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOld", nasIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveOld indicates an expected call of RemoveOld.
func (mr *MockFlowMockRecorder) RemoveOld(nasIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOld", reflect.TypeOf((*MockFlow)(nil).RemoveOld), nasIP)
}
