services:
  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: aggregator
      POSTGRES_PASSWORD: aggregator
      POSTGRES_DB: aggregator
      PGDATA: /data
      TZ: 'GMT+5'
    volumes:
      - ./pg/data:/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aggregator" ]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
  migrate:
    image: migrate/migrate
    command:
      [
        "-path",
        "/migration",
        "-database",
        "postgres://aggregator:aggregator@db:5432/aggregator?sslmode=disable",
        "up",
        "1"
      ]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../docker/migrate:/migration
  core:
    image: ${NAME}:${VERSION}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        VERSION: ${VERSION}
        NAME: ${NAME}
    environment:
      DEBUG: 'true'
      MEASURE: 'enable'
      VERSION: ${VERSION}
      CONF_PATH: "conf.yaml"
      PG_URL: db
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_started
        restart: true
    volumes:
      - ../src/log:/app/log
      - ../src/config/conf.yaml:/app/conf.yaml
      - ../src/flow:/app/flow
      - ../src/subnet-disabled:/app/subnet-disabled
    stop_grace_period: 2s
