// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/usecase/interface.go
//
// Generated by this command:
//
//	mockgen -destination=../internal/usecase/mocks.go -package=usecase -source=../internal/usecase/interface.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	channel "aggregator/src/internal/entity/channel"
	session "aggregator/src/internal/entity/session"
	traffic "aggregator/src/internal/entity/traffic"
	transaction "aggregator/src/internal/transaction"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFlowStreamer is a mock of FlowStreamer interface.
type MockFlowStreamer struct {
	ctrl     *gomock.Controller
	recorder *MockFlowStreamerMockRecorder
	isgomock struct{}
}

// MockFlowStreamerMockRecorder is the mock recorder for MockFlowStreamer.
type MockFlowStreamerMockRecorder struct {
	mock *MockFlowStreamer
}

// NewMockFlowStreamer creates a new mock instance.
func NewMockFlowStreamer(ctrl *gomock.Controller) *MockFlowStreamer {
	mock := &MockFlowStreamer{ctrl: ctrl}
	mock.recorder = &MockFlowStreamerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowStreamer) EXPECT() *MockFlowStreamerMockRecorder {
	return m.recorder
}

// StreamFlow mocks base method.
func (m *MockFlowStreamer) StreamFlow(dirName string, skipFileNames map[string]bool, onLine func(string) error) ([]string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamFlow", dirName, skipFileNames, onLine)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StreamFlow indicates an expected call of StreamFlow.
func (mr *MockFlowStreamerMockRecorder) StreamFlow(dirName, skipFileNames, onLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamFlow", reflect.TypeOf((*MockFlowStreamer)(nil).StreamFlow), dirName, skipFileNames, onLine)
}

// MockSessionLoader is a mock of SessionLoader interface.
type MockSessionLoader struct {
	ctrl     *gomock.Controller
	recorder *MockSessionLoaderMockRecorder
	isgomock struct{}
}

// MockSessionLoaderMockRecorder is the mock recorder for MockSessionLoader.
type MockSessionLoaderMockRecorder struct {
	mock *MockSessionLoader
}

// NewMockSessionLoader creates a new mock instance.
func NewMockSessionLoader(ctrl *gomock.Controller) *MockSessionLoader {
	mock := &MockSessionLoader{ctrl: ctrl}
	mock.recorder = &MockSessionLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionLoader) EXPECT() *MockSessionLoaderMockRecorder {
	return m.recorder
}

// LoadOnlineSessionMap mocks base method.
func (m *MockSessionLoader) LoadOnlineSessionMap(ctx context.Context, ts transaction.Session) (map[session.NasIP][]session.OnlineSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadOnlineSessionMap", ctx, ts)
	ret0, _ := ret[0].(map[session.NasIP][]session.OnlineSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadOnlineSessionMap indicates an expected call of LoadOnlineSessionMap.
func (mr *MockSessionLoaderMockRecorder) LoadOnlineSessionMap(ctx, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadOnlineSessionMap", reflect.TypeOf((*MockSessionLoader)(nil).LoadOnlineSessionMap), ctx, ts)
}

// MockChannelLoader is a mock of ChannelLoader interface.
type MockChannelLoader struct {
	ctrl     *gomock.Controller
	recorder *MockChannelLoaderMockRecorder
	isgomock struct{}
}

// MockChannelLoaderMockRecorder is the mock recorder for MockChannelLoader.
type MockChannelLoaderMockRecorder struct {
	mock *MockChannelLoader
}

// NewMockChannelLoader creates a new mock instance.
func NewMockChannelLoader(ctrl *gomock.Controller) *MockChannelLoader {
	mock := &MockChannelLoader{ctrl: ctrl}
	mock.recorder = &MockChannelLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelLoader) EXPECT() *MockChannelLoaderMockRecorder {
	return m.recorder
}

// LoadChannelMap mocks base method.
func (m *MockChannelLoader) LoadChannelMap(ctx context.Context, ts transaction.Session) (map[channel.ID]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadChannelMap", ctx, ts)
	ret0, _ := ret[0].(map[channel.ID]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadChannelMap indicates an expected call of LoadChannelMap.
func (mr *MockChannelLoaderMockRecorder) LoadChannelMap(ctx, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadChannelMap", reflect.TypeOf((*MockChannelLoader)(nil).LoadChannelMap), ctx, ts)
}

// MockTrafficProcessor is a mock of TrafficProcessor interface.
type MockTrafficProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockTrafficProcessorMockRecorder
	isgomock struct{}
}

// MockTrafficProcessorMockRecorder is the mock recorder for MockTrafficProcessor.
type MockTrafficProcessorMockRecorder struct {
	mock *MockTrafficProcessor
}

// NewMockTrafficProcessor creates a new mock instance.
func NewMockTrafficProcessor(ctrl *gomock.Controller) *MockTrafficProcessor {
	mock := &MockTrafficProcessor{ctrl: ctrl}
	mock.recorder = &MockTrafficProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrafficProcessor) EXPECT() *MockTrafficProcessorMockRecorder {
	return m.recorder
}

// NewFlowAccumulator mocks base method.
func (m *MockTrafficProcessor) NewFlowAccumulator(channelMap map[channel.ID]bool) *FlowAccumulator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFlowAccumulator", channelMap)
	ret0, _ := ret[0].(*FlowAccumulator)
	return ret0
}

// NewFlowAccumulator indicates an expected call of NewFlowAccumulator.
func (mr *MockTrafficProcessorMockRecorder) NewFlowAccumulator(channelMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFlowAccumulator", reflect.TypeOf((*MockTrafficProcessor)(nil).NewFlowAccumulator), channelMap)
}

// SiftTraffic mocks base method.
func (m *MockTrafficProcessor) SiftTraffic(channelMap map[channel.ID]bool, trafficMap map[session.IP]map[channel.ID]traffic.Traffic, sessionList []session.OnlineSession) ([]session.Chunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SiftTraffic", channelMap, trafficMap, sessionList)
	ret0, _ := ret[0].([]session.Chunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SiftTraffic indicates an expected call of SiftTraffic.
func (mr *MockTrafficProcessorMockRecorder) SiftTraffic(channelMap, trafficMap, sessionList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SiftTraffic", reflect.TypeOf((*MockTrafficProcessor)(nil).SiftTraffic), channelMap, trafficMap, sessionList)
}
